### ISSUE TITLE
Bug Report: Greengrass Component Failure

### ISSUE THREAD

**Issue by bml1g12** [awslabs/aws-greengrass-labs-containerized-secure-tunneling#1]
It seems there's a breaking bug in the Greengrass Component for Secure Tunnelling when installing in Raspberry Pi. I appreciate it's not the same software as this repository, but there doesn't seem to be anywhere to post bug reports for that component, so I wanted to raise awareness here:

https://repost.aws/questions/QULkppMLpHRb-zHxLTMVJFFg/aws-greengrass-secure-tunnel-component-fails-to-install

Thank you,

**Comment by HarshGandhi-AWS** [comment]
mean while, can you share the output of `uname -a` and also share the generated error logs with me over here? Thanks.

**Comment by bml1g12** [comment]
Thank you
```
uname -a
Linux mcs-respeaker-3-ca69de 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux
```

```
com.aws.greengrass.component.securetunneling.exceptions.SecureTunnelingTaskException: Unable to determine compatible OS distribution information! Supported OS distributions: [amzn2,ubuntu,raspberrypi]
```

I was able to work around this issue by following one suggestion on that link, but not sure if it might have any adverse consequences. 

Specifically applying the configuration:

```
{
  "reset": [],
  "merge": {
    "OS_DIST_INFO": "ubuntu"
  }
}
```

Given Pi is a common architecture for Greengrass though, very grateful for a proper fix :bow:

**Comment by Nelsonochoam** [comment]
Hey @bml1g12 , what you did is actually the correct approach. Under the hood the container is using the [aws.greengrass.SecureTunneling ](https://docs.aws.amazon.com/greengrass/v2/developerguide/secure-tunneling-component.html) component. 

Under the configuration section you will find some documentation for the `OS_DIST_INFO` configuration parameter.

> By default, the component attempts to automatically identify the operating system running on your core device. If the component fails to start with the default value, then use this value to specify the operating system

the component tries to parse the operating system using the `uname -a` command but we can't guarantee we can successfully determine if the OS listed by the command is one of the ones we support. In those cases, like in yours, it is better to directly tell the component what you are using by providing it in the configuration.

**Comment by HarshGandhi-AWS** [comment]
Hello @bml1g12 , we are closing this issue now. Please feel free to create new issue if you face any issue using Device Client or GG secure Tunneling component.

**Comment by bml1g12** [comment]
@HarshGandhi-AWS Thank you, although this works on 32 bit the issue persists for 64 bit OS. Specifically I noticed that on Rasberry Pi 64 bit (arm64/armv8) neither of:
 
```
{
  "reset": [],
  "merge": {
    "OS_DIST_INFO": "ubuntu"
  }
}
```

And 
```
{
  "reset": [],
  "merge": {
    "OS_DIST_INFO": "raspberrypi"
  }
}
```
work as they _both_  seem to produce 
```
2022-11-08T13:58:44.966Z [INFO] (Copier) aws.greengrass.SecureTunneling: stdout. [ERROR] 2022-11-08 22:58:44.892 [main] SecureTunneling - Exception loading required Secure Tunneling file.. {scriptName=services.aws.greengrass.SecureTunneling.lifecycle.run.script, serviceName=aws.greengrass.SecureTunneling, currentState=RUNNING}
2022-11-08T13:58:44.967Z [INFO] (Copier) aws.greengrass.SecureTunneling: stdout. java.io.FileNotFoundException: Cannot find file: aws.greengrass.SecureTunneling/linux/aarch64/raspberrypi/aws-iot-device-client in archive: /greengrass/v2/packages/artifacts/aws.greengrass.SecureTunneling/1.0.9/GreengrassV2SecureTunnelingComponent-1.0-all.jar. {scriptName=services.aws.greengrass.SecureTunneling.lifecycle.run.script, serviceName=aws.greengrass.SecureTunneling, currentState=RUNNING}
```
i.e. ` Cannot find file: aws.greengrass.SecureTunneling/linux/aarch64/raspberrypi/aws-iot-device-client`

Introspecting the .jar file:

![image](https://user-images.githubusercontent.com/2605767/200586339-f4de7bcd-2a8e-4c2b-adfe-1a116dd5986e.png)

It looks to me like there is an aarch64 build for ubuntu but not raspberry pi. I don't understand why despite specifying the OS as ubuntu it is trying to look into a `raspberry/` subfolder for this file. Does the Secure Tunnel not support raspberry pi 64 bit?

It seems that in the case of specifying merge `ubuntu`, the resulting configuration ends up going to "auto":
```
Component Name: aws.greengrass.SecureTunneling
    Version: 1.0.9
    State: BROKEN
    Configuration: {"accessControl":{"aws.greengrass.ipc.mqttproxy":{"aws.greengrass.SecureTunneling:mqttproxy:1":{"operations":["aws.greengrass#SubscribeToIoTCore"],"policyDescription":"Access to tunnel notification pubsub topic","resources":["$aws/things/+/tunnels/notify"]}}},"merge":{"OS_DIST_INFO":"ubuntu"},"OS_DIST_INFO":"auto","reset":[]}
```


I notice the OP of [that thread](https://repost.aws/questions/QULkppMLpHRb-zHxLTMVJFFg/aws-greengrass-secure-tunnel-component-fails-to-install) was also using 64 bit OS, so I'm unclear if this was resolved for them.
